require_relative 'model/category'
require_relative 'model/discourse'
require_relative 'model/file'
require_relative 'model/folder'
require_relative 'model/group'
require_relative 'model/group_discourse_permission'
require_relative 'model/group_file_permission'
require_relative 'model/group_folder_permission'
require_relative 'model/language'
require_relative 'model/license'
require_relative 'model/link'
require_relative 'model/person'
require_relative 'model/person_discourse_permission'
require_relative 'model/person_file_permission'
require_relative 'model/person_folder_permission'
require_relative 'model/tag'
require_relative 'model/utterance'

